version: '3.7'

services:
  redis:
    image: redis
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
    entrypoint:
      - ./entrypoint.sh


  nginx:
    build: ./nginx

    volumes:
      - static_volume:/app/static
    ports:
      - 8001:8001
    depends_on:
      - web


#  worker:
#    restart: always
#    build:
#      context: .
#    volumes:
#      - ./cats:/app/src/cats
#    command: [ 'celery', '--workdir=.', '-A', 'kredit', 'worker' ]

volumes:
  static_volume: